# Modified from https://github.com/JingyunLiang/SwinIR
# SwinIR: Image Restoration Using Swin Transformer, https://arxiv.org/abs/2108.10257
# Originally Written by Ze Liu, Modified by Jingyun Liang.
'''
SwinIR: Image Restoration Using Swin Transformer
Code Reference: https://github.com/JingyunLiang/SwinIR
'''

import collections.abc
import math
import torch
import torch.nn as nn
import torch.utils.checkpoint as checkpoint
import warnings
import numpy as np
import torch.nn.functional as F
from itertools import repeat
from mmdet.registry import MODELS

def _ntuple(n):
    def parse(x):
        if isinstance(x, collections.abc.Iterable):
            return x
        return tuple(repeat(x, n))

    return parse


to_2tuple = _ntuple(2)


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/weight_init.py
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            'mean is more than 2 std from [a, b] in nn.init.trunc_normal_. '
            'The distribution of values may be incorrect.',
            stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        low = norm_cdf((a - mean) / std)
        up = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [low, up], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * low - 1, 2 * up - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution.

    From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/weight_init.py

    The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.

    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value

    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def drop_path(x, drop_prob: float = 0., training: bool = False):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).

    From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/drop.py
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).

    From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/drop.py
    """

    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)


class Mlp(nn.Module):

    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class TransposedConvUpsample(nn.Module):
    """ Upsampling Layer with Transposed Convolution
    Args:
        dim (int): Number of input channels.
        out_dim (int): Number of output channels.
        scale_factor (int): Scaling factor to expand spatial dimensions. Default: 2
    """

    def __init__(self, dim, out_dim, scale_factor=2, norm_layer=nn.LayerNorm):
        super().__init__()
        self.scale_factor = scale_factor
        self.norm = norm_layer(dim)

        # Define transposed convolution
        self.upconv = nn.ConvTranspose2d(
            in_channels=dim,
            out_channels=out_dim,
            kernel_size=scale_factor,
            stride=scale_factor,
            padding=0,
            output_padding=0,
            bias=False
        )

    def forward(self, x, H, W):
        """ Forward function.
        Args:
            x: Input feature, tensor size (B, H/2*W/2, C).
            H, W: Target spatial resolution after upsampling.
        """
        B, L, C = x.shape
        assert L == H * W, "input feature has wrong size"

        # Normalize input
        x = self.norm(x)

        # Reshape x to (B, C, H//scale_factor, W//scale_factor) for ConvTranspose2d
        x = x.view(B, H, W, C).permute(0, 3, 1, 2)

        # Apply transposed convolution to upsample
        x = self.upconv(x)  # Output shape should be (B, out_dim, H, W)
        B, C, H, W = x.shape

        # Reshape x back to (B, H * W, out_dim) to match the original input format
        x = x.permute(0, 2, 3, 1).contiguous().view(B, H * W, -1)

        return x, H, W


def window_partition(x, window_size):
    """
    Args:
        x: (b, h, w, c)
        window_size (int): window size

    Returns:
        windows: (num_windows*b, window_size, window_size, c)
    """
    b, h, w, c = x.shape
    x = x.view(b, h // window_size, window_size, w // window_size, window_size, c)
    windows = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(-1, window_size, window_size, c)
    return windows


def window_reverse(windows, window_size, h, w):
    """
    Args:
        windows: (num_windows*b, window_size, window_size, c)
        window_size (int): Window size
        h (int): Height of image
        w (int): Width of image

    Returns:
        x: (b, h, w, c)
    """
    b = int(windows.shape[0] / (h * w / window_size / window_size))
    x = windows.view(b, h // window_size, w // window_size, window_size, window_size, -1)
    x = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(b, h, w, -1)
    return x


class WindowAttention(nn.Module):
    r""" Window based multi-head self attention (W-MSA) module with relative position bias.
    It supports both of shifted and non-shifted window.

    Args:
        dim (int): Number of input channels.
        window_size (tuple[int]): The height and width of the window.
        num_heads (int): Number of attention heads.
        qkv_bias (bool, optional):  If True, add a learnable bias to query, key, value. Default: True
        qk_scale (float | None, optional): Override default qk scale of head_dim ** -0.5 if set
        attn_drop (float, optional): Dropout ratio of attention weight. Default: 0.0
        proj_drop (float, optional): Dropout ratio of output. Default: 0.0
    """

    def __init__(self, dim, window_size, num_heads, qkv_bias=True, qk_scale=None, attn_drop=0., proj_drop=0.):

        super().__init__()
        self.dim = dim
        self.window_size = window_size  # Wh, Ww
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5

        # define a parameter table of relative position bias
        self.relative_position_bias_table = nn.Parameter(
            torch.zeros((2 * window_size[0] - 1) * (2 * window_size[1] - 1), num_heads))  # 2*Wh-1 * 2*Ww-1, nH

        # get pair-wise relative position index for each token inside the window
        coords_h = torch.arange(self.window_size[0])
        coords_w = torch.arange(self.window_size[1])
        coords = torch.stack(torch.meshgrid([coords_h, coords_w]))  # 2, Wh, Ww
        coords_flatten = torch.flatten(coords, 1)  # 2, Wh*Ww
        relative_coords = coords_flatten[:, :, None] - coords_flatten[:, None, :]  # 2, Wh*Ww, Wh*Ww
        relative_coords = relative_coords.permute(1, 2, 0).contiguous()  # Wh*Ww, Wh*Ww, 2
        relative_coords[:, :, 0] += self.window_size[0] - 1  # shift to start from 0
        relative_coords[:, :, 1] += self.window_size[1] - 1
        relative_coords[:, :, 0] *= 2 * self.window_size[1] - 1
        relative_position_index = relative_coords.sum(-1)  # Wh*Ww, Wh*Ww
        self.register_buffer('relative_position_index', relative_position_index)

        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)

        self.proj_drop = nn.Dropout(proj_drop)

        trunc_normal_(self.relative_position_bias_table, std=.02)
        self.softmax = nn.Softmax(dim=-1)

    def forward(self, x, mask=None):
        """
        Args:
            x: input features with shape of (num_windows*b, n, c)
            mask: (0/-inf) mask with shape of (num_windows, Wh*Ww, Wh*Ww) or None
        """
        b_, n, c = x.shape
        qkv = self.qkv(x).reshape(b_, n, 3, self.num_heads, c // self.num_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]  # make torchscript happy (cannot use tensor as tuple)

        q = q * self.scale
        attn = (q @ k.transpose(-2, -1))

        relative_position_bias = self.relative_position_bias_table[self.relative_position_index.view(-1)].view(
            self.window_size[0] * self.window_size[1], self.window_size[0] * self.window_size[1], -1)  # Wh*Ww,Wh*Ww,nH
        relative_position_bias = relative_position_bias.permute(2, 0, 1).contiguous()  # nH, Wh*Ww, Wh*Ww
        attn = attn + relative_position_bias.unsqueeze(0)

        if mask is not None:
            nw = mask.shape[0]
            attn = attn.view(b_ // nw, nw, self.num_heads, n, n) + mask.unsqueeze(1).unsqueeze(
                0)  # mask 原本形状为 (nw, Wh*Ww, Wh*Ww)，通过 unsqueeze(1) 和 unsqueeze(0)，形状变为 (1, nw, 1, n, n)，使其可以与 attn 相加
            attn = attn.view(-1, self.num_heads, n, n)
            attn = self.softmax(attn)
        else:
            attn = self.softmax(attn)

        attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).reshape(b_, n, c)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x

    def extra_repr(self) -> str:
        return f'dim={self.dim}, window_size={self.window_size}, num_heads={self.num_heads}'

    def flops(self, n):
        # calculate flops for 1 window with token length of n
        flops = 0
        # qkv = self.qkv(x)
        flops += n * self.dim * 3 * self.dim
        # attn = (q @ k.transpose(-2, -1))
        flops += self.num_heads * n * (self.dim // self.num_heads) * n
        #  x = (attn @ v)
        flops += self.num_heads * n * n * (self.dim // self.num_heads)
        # x = self.proj(x)
        flops += n * self.dim * self.dim
        return flops


class SwinTransformerBlock(nn.Module):
    r""" Swin Transformer Block.

    Args:
        dim (int): Number of input channels.
        input_resolution (tuple[int]): Input resolution.
        num_heads (int): Number of attention heads.
        window_size (int): Window size.
        shift_size (int): Shift size for SW-MSA.
        mlp_ratio (float): Ratio of mlp hidden dim to embedding dim.
        qkv_bias (bool, optional): If True, add a learnable bias to query, key, value. Default: True
        qk_scale (float | None, optional): Override default qk scale of head_dim ** -0.5 if set.
        drop (float, optional): Dropout rate. Default: 0.0
        attn_drop (float, optional): Attention dropout rate. Default: 0.0
        drop_path (float, optional): Stochastic depth rate. Default: 0.0
        act_layer (nn.Module, optional): Activation layer. Default: nn.GELU
        norm_layer (nn.Module, optional): Normalization layer.  Default: nn.LayerNorm
    """

    def __init__(self,
                 dim,
                 # input_resolution,
                 num_heads,
                 window_size=7,
                 shift_size=0,
                 mlp_ratio=4.,
                 qkv_bias=True,
                 qk_scale=None,
                 drop=0.,
                 attn_drop=0.,
                 drop_path=0.,
                 act_layer=nn.GELU,
                 norm_layer=nn.LayerNorm):
        super().__init__()
        self.dim = dim
        # self.input_resolution = input_resolution
        self.num_heads = num_heads
        self.window_size = window_size
        self.shift_size = shift_size
        self.mlp_ratio = mlp_ratio
        # if min(self.input_resolution) <= self.window_size:
        #     # if window size is larger than input resolution, we don't partition windows
        #     self.shift_size = 0
        #     self.window_size = min(self.input_resolution)
        assert 0 <= self.shift_size < self.window_size, 'shift_size must in 0-window_size'

        self.norm9 = norm_layer(dim)
        self.attn = WindowAttention(
            dim,
            window_size=to_2tuple(self.window_size),
            num_heads=num_heads,
            qkv_bias=qkv_bias,
            qk_scale=qk_scale,
            attn_drop=attn_drop,
            proj_drop=drop)

        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer, drop=drop)

        # if self.shift_size > 0:
        #     attn_mask = self.calculate_mask(self.input_resolution)
        # else:
        #     attn_mask = None
        #
        # self.register_buffer('attn_mask', attn_mask)

    # def calculate_mask(self, x_size):
    #     # calculate attention mask for SW-MSA
    #     # h = H
    #     # w = W
    #
    #     h, w = x_size
    #     img_mask = torch.zeros((1, h, w, 1))  # 1 h w 1
    #     h_slices = (slice(0, -self.window_size), slice(-self.window_size,
    #                                                    -self.shift_size), slice(-self.shift_size, None))
    #     w_slices = (slice(0, -self.window_size), slice(-self.window_size,
    #                                                    -self.shift_size), slice(-self.shift_size, None))
    #     cnt = 0
    #     for h in h_slices:
    #         for w in w_slices:
    #             img_mask[:, h, w, :] = cnt
    #             cnt += 1
    #
    #     mask_windows = window_partition(img_mask, self.window_size)  # nw, window_size, window_size, 1
    #     mask_windows = mask_windows.view(-1, self.window_size * self.window_size)
    #     attn_mask = mask_windows.unsqueeze(1) - mask_windows.unsqueeze(2)
    #     attn_mask = attn_mask.masked_fill(attn_mask != 0, float(-100.0)).masked_fill(attn_mask == 0, float(0.0))
    #
    #     return attn_mask

    def forward(self, x, H, W, mask_matrix):
        h = H
        w = W
        b, _, c = x.shape
        assert _ == h * w, "input feature has wrong size"

        shortcut = x
        x = self.norm9(x)
        x = x.view(b, h, w, c)

        # pad feature maps to multiples of window size
        pad_l = pad_t = 0
        pad_r = (self.window_size - W % self.window_size) % self.window_size
        pad_b = (self.window_size - H % self.window_size) % self.window_size
        x = F.pad(x, (0, 0, pad_l, pad_r, pad_t, pad_b))
        _, Hp, Wp, _ = x.shape

        # cyclic shift
        if self.shift_size > 0:
            shifted_x = torch.roll(x, shifts=(-self.shift_size, -self.shift_size), dims=(1, 2))
            attn_mask = mask_matrix
        else:
            shifted_x = x
            attn_mask = None

        # partition windows
        x_windows = window_partition(shifted_x, self.window_size)  # nw*b, window_size, window_size, c
        x_windows = x_windows.view(-1, self.window_size * self.window_size, c)  # nw*b, window_size*window_size, c

        # W-MSA/SW-MSA (to be compatible for testing on images whose shapes are the multiple of window size
        # if self.input_resolution == x_size:
        #     attn_windows = self.attn(x_windows, mask=self.attn_mask)  # nw*b, window_size*window_size, c
        # else:
        #     attn_windows = self.attn(x_windows, mask=self.calculate_mask(x_size).to(x.device))
        # W-MSA/SW-MSA
        attn_windows = self.attn(x_windows, mask=attn_mask)  # nW*B, window_size*window_size, C

        # merge windows
        attn_windows = attn_windows.view(-1, self.window_size, self.window_size, c)
        shifted_x = window_reverse(attn_windows, self.window_size, Hp, Wp)  # b h' w' c

        # reverse cyclic shift
        if self.shift_size > 0:
            x = torch.roll(shifted_x, shifts=(self.shift_size, self.shift_size), dims=(1, 2))
        else:
            x = shifted_x

        if pad_r > 0 or pad_b > 0:
            x = x[:, :H, :W, :].contiguous()

        x = x.view(b, h * w, c)

        # FFN
        x = shortcut + self.drop_path(x)
        x = x + self.drop_path(self.mlp(self.norm2(x)))

        return x

    def extra_repr(self) -> str:
        return (f'dim={self.dim}, num_heads={self.num_heads}, '
                f'window_size={self.window_size}, shift_size={self.shift_size}, mlp_ratio={self.mlp_ratio}')

    def flops(self):
        flops = 0
        h, w = self.input_resolution
        # norm1
        flops += self.dim * h * w
        # W-MSA/SW-MSA
        nw = h * w / self.window_size / self.window_size
        flops += nw * self.attn.flops(self.window_size * self.window_size)
        # mlp
        flops += 2 * h * w * self.dim * self.dim * self.mlp_ratio
        # norm2
        flops += self.dim * h * w
        return flops


class BasicUpLayer(nn.Module):
    """ A basic Swin Transformer layer for one stage.

    Args:
        dim (int): Number of input channels.
        input_resolution (tuple[int]): Input resolution.
        depth (int): Number of blocks.
        num_heads (int): Number of attention heads.
        window_size (int): Local window size.
        mlp_ratio (float): Ratio of mlp hidden dim to embedding dim.
        qkv_bias (bool, optional): If True, add a learnable bias to query, key, value. Default: True
        qk_scale (float | None, optional): Override default qk scale of head_dim ** -0.5 if set.
        drop (float, optional): Dropout rate. Default: 0.0
        attn_drop (float, optional): Attention dropout rate. Default: 0.0
        drop_path (float | tuple[float], optional): Stochastic depth rate. Default: 0.0
        norm_layer (nn.Module, optional): Normalization layer. Default: nn.LayerNorm
        downsample (nn.Module | None, optional): Downsample layer at the end of the layer. Default: None
        use_checkpoint (bool): Whether to use checkpointing to save memory. Default: False.
    """

    def __init__(self,
                 dim,
                 # input_resolution,
                 depth,
                 num_heads,
                 window_size,
                 mlp_ratio=4.,
                 qkv_bias=True,
                 qk_scale=None,
                 drop=0.,
                 attn_drop=0.,
                 drop_path=0.,
                 norm_layer=nn.LayerNorm,
                 upsample=None,
                 use_checkpoint=False,
                 out_dim=None):

        super().__init__()
        self.dim = dim
        self.window_size = window_size
        # self.input_resolution = input_resolution
        self.shift_size = window_size // 2
        self.depth = depth
        self.use_checkpoint = use_checkpoint

        # build blocks
        self.blocks = nn.ModuleList([
            SwinTransformerBlock(
                dim=dim,
                # input_resolution=input_resolution,
                num_heads=num_heads,
                window_size=window_size,
                shift_size=0 if (i % 2 == 0) else window_size // 2,
                mlp_ratio=mlp_ratio,
                qkv_bias=qkv_bias,
                qk_scale=qk_scale,
                drop=drop,
                attn_drop=attn_drop,
                drop_path=drop_path[i] if isinstance(drop_path, list) else drop_path,
                norm_layer=norm_layer) for i in range(depth)
        ])

        # patch merging layer
        # if upsample is not None:
        #     self.upsample = upsample(dim=dim, out_dim=dim // 2, norm_layer=norm_layer)
        # else:
        #     self.upsample = None

    def forward(self, x, H, W):

        # calculate attention mask for SW-MSA
        Hp = int(np.ceil(H / self.window_size)) * self.window_size
        Wp = int(np.ceil(W / self.window_size)) * self.window_size
        img_mask = torch.zeros((1, Hp, Wp, 1), device=x.device)  # 1 Hp Wp 1
        h_slices = (slice(0, -self.window_size),
                    slice(-self.window_size, -self.shift_size),
                    slice(-self.shift_size, None))
        w_slices = (slice(0, -self.window_size),
                    slice(-self.window_size, -self.shift_size),
                    slice(-self.shift_size, None))
        cnt = 0
        for h in h_slices:
            for w in w_slices:
                img_mask[:, h, w, :] = cnt
                cnt += 1

        mask_windows = window_partition(img_mask, self.window_size)  # nW, window_size, window_size, 1
        mask_windows = mask_windows.view(-1, self.window_size * self.window_size)
        attn_mask = mask_windows.unsqueeze(1) - mask_windows.unsqueeze(2)
        attn_mask = attn_mask.masked_fill(attn_mask != 0, float(-100.0)).masked_fill(attn_mask == 0, float(0.0))

        # for blk in self.blocks:
        #     blk.H, blk.W = H, W
        #     if self.use_checkpoint:
        #         x = checkpoint.checkpoint(blk, x, attn_mask)
        #     else:
        #         x = blk(x, attn_mask)

        for blk in self.blocks:
            if self.use_checkpoint:
                x = checkpoint.checkpoint(blk, x, attn_mask)
            else:
                x = blk(x, H, W, attn_mask)
        # if self.downsample is not None:
        #     x = self.downsample(x)
        return x

    def extra_repr(self) -> str:
        return f'dim={self.dim}, depth={self.depth}'

    def flops(self):
        flops = 0
        for blk in self.blocks:
            flops += blk.flops()
        if self.downsample is not None:
            flops += self.downsample.flops()
        return flops


# class PatchEmbed(nn.Module):
#     r""" Image to Patch Embedding
#
#     Args:
#         img_size (int): Image size.  Default: 224.
#         patch_size (int): Patch token size. Default: 4.
#         in_chans (int): Number of input image channels. Default: 3.
#         embed_dim (int): Number of linear projection output channels. Default: 96.
#         norm_layer (nn.Module, optional): Normalization layer. Default: None
#     """
#
#     def __init__(self, img_size=224, patch_size=4, in_chans=3, embed_dim=96, norm_layer=None):
#         super().__init__()
#         img_size = to_2tuple(img_size)
#         patch_size = to_2tuple(patch_size)
#         patches_resolution = [img_size[0] // patch_size[0], img_size[1] // patch_size[1]]
#         self.img_size = img_size
#         self.patch_size = patch_size
#         self.patches_resolution = patches_resolution
#         self.num_patches = patches_resolution[0] * patches_resolution[1]
#
#         self.in_chans = in_chans
#         self.embed_dim = embed_dim
#
#         if norm_layer is not None:
#             self.norm = norm_layer(embed_dim)
#         else:
#             self.norm = None
#
#     def forward(self, x):
#         x = x.flatten(2).transpose(1, 2)  # b Ph*Pw c
#         # print("x_bPh*Pwc_shape:", x.shape)
#         if self.norm is not None:
#             x = self.norm(x)
#         return x
#
#     def flops(self):
#         flops = 0
#         h, w = self.img_size
#         if self.norm is not None:
#             flops += h * w * self.embed_dim
#         return flops


class PatchUnEmbed(nn.Module):
    r""" Image to Patch Unembedding

    Args:
        img_size (int): Image size.  Default: 224.
        patch_size (int): Patch token size. Default: 4.
        in_chans (int): Number of input image channels. Default: 3.
        embed_dim (int): Number of linear projection output channels. Default: 96.
        norm_layer (nn.Module, optional): Normalization layer. Default: None
    """

    def __init__(self, img_size=224, patch_size=4, in_chans=3, embed_dim=96, norm_layer=None):
        super().__init__()
        img_size = to_2tuple(img_size)
        patch_size = to_2tuple(patch_size)
        patches_resolution = [img_size[0] // patch_size[0], img_size[1] // patch_size[1]]
        self.img_size = img_size
        self.patch_size = patch_size
        self.patches_resolution = patches_resolution
        self.num_patches = patches_resolution[0] * patches_resolution[1]

        # self.norm = norm_layer(embed_dim)

        self.proj = nn.ConvTranspose2d(embed_dim, 32, kernel_size=patch_size, stride=patch_size)

        self.in_chans = in_chans
        self.embed_dim = embed_dim

    def forward(self, x, H, W):
        x = x.transpose(1, 2).view(x.shape[0], self.embed_dim, H, W)  # b Ph*Pw c

        x = self.proj(x)

        return x

    def flops(self):
        flops = 0
        return flops


class Upsample(nn.Sequential):
    """Upsample module.

    Args:
        scale (int): Scale factor. Supported scales: 2^n and 3.
        num_feat (int): Channel number of intermediate features.
    """

    def __init__(self, scale, num_feat):
        m = []
        if (scale & (scale - 1)) == 0:  # scale = 2^n
            for _ in range(int(math.log(scale, 2))):
                m.append(nn.Conv2d(num_feat, 4 * num_feat, 3, 1, 1))
                m.append(nn.PixelShuffle(2))
        elif scale == 3:
            m.append(nn.Conv2d(num_feat, 9 * num_feat, 3, 1, 1))
            m.append(nn.PixelShuffle(3))
        else:
            raise ValueError(f'scale {scale} is not supported. Supported scales: 2^n and 3.')
        super(Upsample, self).__init__(*m)


class UpsampleOneStep(nn.Sequential):
    """UpsampleOneStep module (the difference with Upsample is that it always only has 1conv + 1pixelshuffle)
       Used in lightweight SR to save parameters.

    Args:
        scale (int): Scale factor. Supported scales: 2^n and 3.
        num_feat (int): Channel number of intermediate features.

    """

    def __init__(self, scale, num_feat, num_out_ch, input_resolution=None):
        self.num_feat = num_feat
        self.input_resolution = input_resolution
        m = []
        m.append(nn.Conv2d(num_feat, (scale ** 2) * num_out_ch, 3, 1, 1))
        m.append(nn.PixelShuffle(scale))
        super(UpsampleOneStep, self).__init__(*m)

    def flops(self):
        h, w = self.input_resolution
        flops = h * w * self.num_feat * 3 * 9
        return flops

@MODELS.register_module()
class SRNet(nn.Module):
    r""" SwinIR
        A PyTorch impl of : `SwinIR: Image Restoration Using Swin Transformer`, based on Swin Transformer.

    Args:
        img_size (int | tuple(int)): Input image size. Default 64
        patch_size (int | tuple(int)): Patch size. Default: 1
        in_chans (int): Number of input image channels. Default: 3
        embed_dim (int): Patch embedding dimension. Default: 96
        depths (tuple(int)): Depth of each Swin Transformer layer.
        num_heads (tuple(int)): Number of attention heads in different layers.
        window_size (int): Window size. Default: 7
        mlp_ratio (float): Ratio of mlp hidden dim to embedding dim. Default: 4
        qkv_bias (bool): If True, add a learnable bias to query, key, value. Default: True
        qk_scale (float): Override default qk scale of head_dim ** -0.5 if set. Default: None
        drop_rate (float): Dropout rate. Default: 0
        attn_drop_rate (float): Attention dropout rate. Default: 0
        drop_path_rate (float): Stochastic depth rate. Default: 0.1
        norm_layer (nn.Module): Normalization layer. Default: nn.LayerNorm.
        ape (bool): If True, add absolute position embedding to the patch embedding. Default: False
        patch_norm (bool): If True, add normalization after patch embedding. Default: True
        use_checkpoint (bool): Whether to use checkpointing to save memory. Default: False
        upscale: Upscale factor. 2/3/4/8 for image SR, 1 for denoising and compress artifact reduction
        img_range: Image range. 1. or 255.
        upsampler: The reconstruction reconstruction module. 'pixelshuffle'/'pixelshuffledirect'/'nearest+conv'/None
        resi_connection: The convolutional block before residual connection. '1conv'/'3conv'
    """

    def __init__(self,
                 # dim,
                 img_size=64,
                 patch_size=4,
                 in_chans=3,
                 embed_dim=96,
                 depths=(6, 2, 2),
                 num_heads=(12, 6, 3),
                 window_size=7,
                 mlp_ratio=4.,
                 qkv_bias=True,
                 qk_scale=None,
                 drop_rate=0.,
                 attn_drop_rate=0.,
                 drop_path_rate=0.1,
                 norm_layer=nn.LayerNorm,
                 ape=False,
                 patch_norm=True,
                 use_checkpoint=False,
                 upscale=2,
                 out_indices=(0, 1, 2),
                 img_range=1.,
                 upsampler='pixelshuffle',
                 resi_connection='1conv',
                 upsample=TransposedConvUpsample,
                 **kwargs):
        super(SRNet, self).__init__()
        num_in_ch = in_chans
        num_out_ch = in_chans
        num_feat = 16
        self.img_range = img_range
        if in_chans == 3:
            rgb_mean = (0.4488, 0.4371, 0.4040)
            self.mean = torch.Tensor(rgb_mean).view(1, 3, 1, 1)
        else:
            self.mean = torch.zeros(1, 1, 1, 1)
        self.upscale = upscale
        self.upsample = upsample
        self.upsampler = upsampler
        self.window_size = window_size

        # ------------------------- 1, shallow feature extraction ------------------------- #
        # self.backbone = build_backbone(**kwargs)

        # ------------------------- 2, deep feature extraction ------------------------- #
        self.num_layers_up = len(depths)
        self.embed_dim = embed_dim
        self.ape = ape
        self.patch_norm = patch_norm
        # self.num_features = embed_dim
        self.mlp_ratio = mlp_ratio

        # split image into non-overlapping patches
        # self.patch_embed = PatchEmbed(
        #     img_size=img_size,
        #     patch_size=patch_size,
        #     in_chans=embed_dim,
        #     embed_dim=embed_dim,
        #     norm_layer=norm_layer if self.patch_norm else None)
        # num_patches = self.patch_embed.num_patches
        # patches_resolution = self.patch_embed.patches_resolution
        # self.patches_resolution = patches_resolution

        # merge non-overlapping patches into image
        self.patch_unembed = PatchUnEmbed(
            img_size=img_size,
            patch_size=patch_size,
            in_chans=embed_dim,
            embed_dim=96,
            norm_layer=norm_layer if self.patch_norm else None)

        # absolute position embedding
        # if self.ape:
        #     self.absolute_pos_embed = nn.Parameter(torch.zeros(1, num_patches, embed_dim))
        #     trunc_normal_(self.absolute_pos_embed, std=.02)

        self.pos_drop = nn.Dropout(p=drop_rate)

        # stochastic depth
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, sum(depths))]  # stochastic depth decay rule

        # build Residual Swin Transformer blocks (RSTB)
        self.layers = nn.ModuleList()

        upsamplelist = [TransposedConvUpsample for i in range(self.num_layers_up)]
        num_features = [int(embed_dim // 2 ** i) for i in range(self.num_layers_up)]

        for i_layer in range(self.num_layers_up):
            layer = BasicUpLayer(
                # dim=int(embed_dim * 2 ** i_layer),
                # input_resolution=(patches_resolution[0], patches_resolution[1]),
                dim=num_features[i_layer],
                depth=depths[i_layer],
                num_heads=num_heads[i_layer],
                window_size=window_size,
                mlp_ratio=mlp_ratio,
                qkv_bias=qkv_bias,
                qk_scale=qk_scale,
                drop=drop_rate,
                attn_drop=attn_drop_rate,
                drop_path=dpr[sum(depths[:i_layer]):sum(depths[:i_layer + 1])],
                norm_layer=norm_layer,
                # downsample=PatchMerging if (i_layer < self.num_layers - 1) else None,
                # upsample=upsamplelist[i_layer],
                use_checkpoint=use_checkpoint)
            self.layers.append(layer)

        # self.i = 0
        self.num_features = num_features
        # self.dim = self.num_features[self.i]
        self.norm = norm_layer(self.num_features[2] // 2)

        if self.upsample is not None:
            self.up_layer_pre = self.upsample(dim=2 * self.num_features[0], out_dim=self.num_features[0],
                                              norm_layer=norm_layer)
            self.up_layer0 = self.upsample(dim=self.num_features[0], out_dim=self.num_features[0] // 2,
                                           norm_layer=norm_layer)
            self.up_layer1 = self.upsample(dim=self.num_features[1], out_dim=self.num_features[1] // 2,
                                           norm_layer=norm_layer)
            self.up_layer2 = self.upsample(dim=self.num_features[2], out_dim=self.num_features[2] // 2,
                                           norm_layer=norm_layer)
        else:
            self.up_layer = None

        # add a norm layer for each output
        for i_layer in out_indices:
            layer = norm_layer(num_features[i_layer])
            layer_name = f'norm{i_layer}'
            self.add_module(layer_name, layer)

        input_proj_list = []
        hidden_dim = 256
        self.in_channels = [768, 384, 192, 96]
        for i in range(4):
            # in_channels = [768, 384, 192]
            input_proj_list.append(nn.Sequential(
                nn.Conv2d(self.in_channels[i], hidden_dim, kernel_size=1),
                nn.GroupNorm(32, hidden_dim),
            ))
        self.input_proj_sr = nn.ModuleList(input_proj_list)

        # self._freeze_stages()
        #
        # def _freeze_stages(self):
        #     if self.frozen_stages >= 0:
        #         self.patch_embed.eval()
        #         for param in self.patch_embed.parameters():
        #             param.requires_grad = False
        #
        #     if self.frozen_stages >= 1 and self.ape:
        #         self.absolute_pos_embed.requires_grad = False
        #
        #     if self.frozen_stages >= 2:
        #         self.pos_drop.eval()
        #         for i in range(0, self.frozen_stages - 1):
        #             m = self.layers[i]
        #             m.eval()
        #             for param in m.parameters():
        #                 param.requires_grad = False

        # build the last conv layer in deep feature extraction

        self.sr_module = nn.Sequential(
            nn.Conv2d(embed_dim // 24, embed_dim // 24, 3, 1, 1),  # conv_after_body
            nn.Conv2d(embed_dim // 24, num_feat, 3, 1, 1),  # conv_before_upsample 1
            nn.LeakyReLU(inplace=True),  # conv_before_upsample 2
            Upsample(upscale, num_feat),  # upsample
            nn.Conv2d(num_feat, num_out_ch, 3, 1, 1)  # conv_last
        )

        # if resi_connection == '1conv':
        #     self.conv_after_body = nn.Conv2d(embed_dim//24, embed_dim//24, 3, 1, 1)
        # elif resi_connection == '3conv':
        #     # to save parameters and memory
        #     self.conv_after_body = nn.Sequential(
        #         nn.Conv2d(embed_dim, embed_dim // 4, 3, 1, 1), nn.LeakyReLU(negative_slope=0.2, inplace=True),
        #         nn.Conv2d(embed_dim // 4, embed_dim // 4, 1, 1, 0), nn.LeakyReLU(negative_slope=0.2, inplace=True),
        #         nn.Conv2d(embed_dim // 4, embed_dim, 3, 1, 1))
        #
        # # ------------------------- 3, high quality image reconstruction ------------------------- #
        # if self.upsampler == 'pixelshuffle':
        #     # for classical SR
        #     self.conv_before_upsample = nn.Sequential(
        #         nn.Conv2d(embed_dim//24, num_feat, 3, 1, 1), nn.LeakyReLU(inplace=True))
        #     self.upsample = Upsample(upscale, num_feat)
        #     self.conv_last = nn.Conv2d(num_feat, num_out_ch, 3, 1, 1)

        self.apply(self._init_weights)
        self._reset_parameters()

    def _reset_parameters(self):
        # init input_proj 用于初始化 input_proj 的权重和偏置值
        for proj in self.input_proj_sr:
            nn.init.xavier_uniform_(proj[0].weight, gain=1)
            nn.init.constant_(proj[0].bias, 0)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    @torch.jit.ignore
    def no_weight_decay(self):
        return {'absolute_pos_embed'}

    @torch.jit.ignore
    def no_weight_decay_keywords(self):
        return {'relative_position_bias_table'}

    # def align_and_add(self, x1, x2, H1, W1, mode='bilinear'):
    #     """
    #     Align x2 to x1 spatial size and add. Inputs are (B, L, C).
    #     H1, W1 are the spatial size for x1 (the larger one).
    #     """
    #     B, L1, C = x1.shape
    #     B2, L2, C2 = x2.shape
    #     assert B == B2 and C == C2, "Batch or channel mismatch"
    #
    #     # 恢复空间尺寸 (B, C, H, W)
    #     H2 = int(L2 ** 0.5)
    #     W2 = L2 // H2
    #     x2_ = x2.transpose(1, 2).contiguous().view(B, C, H2, W2)
    #     x2_resized = F.interpolate(x2_, size=(H1, W1), mode=mode, align_corners=False)
    #
    #     x1_ = x1.transpose(1, 2).contiguous().view(B, C, H1, W1)
    #
    #     out = x1_ + x2_resized
    #     return out.flatten(2).transpose(1, 2).contiguous()  # (B, L, C)

    def align_and_add(self,
                      x1: torch.Tensor,
                      x2: torch.Tensor,
                      H1: int,
                      W1: int,
                      hw_shapes: list[tuple[int, int]],
                      hw_shapes_idx: int,
                      mode: str = 'bilinear'):
        """
        Align x2 to x1 (spatial) and add, then return (B, L, C).
        `x1`, `x2` are (B, L, C).
        `H1`, `W1` are spatial dims of x1.
        `hw_shapes[hw_shapes_idx]` gives spatial dims of x2.
        """
        B, L1, C = x1.shape
        B2, L2, C2 = x2.shape
        assert B == B2 and C == C2, f'Batch/Channel mismatch: {x1.shape}, {x2.shape}'

        # -------- 获取 x1、x2 空间尺寸 --------
        H2, W2 = hw_shapes[hw_shapes_idx]
        assert H2 * W2 == L2, f'Invalid shape: H2×W2={H2 * W2} ≠ L2={L2}'

        # Reshape to image format
        x1_img = x1.transpose(1, 2).contiguous().view(B, C, H1, W1)
        x2_img = x2.transpose(1, 2).contiguous().view(B, C, H2, W2)

        # Upsample x2 to x1 size
        x2_up = F.interpolate(x2_img, size=(H1, W1), mode=mode, align_corners=False)

        # Element-wise addition and reshape back
        out = x1_img + x2_up
        return out.flatten(2).transpose(1, 2).contiguous()
    def forward_features(self, res_x, res_x4,hw_shapes):
        # tensor = res_x[-1]
        # x_size = (tensor.shape[2], tensor.shape[3])
        # print("x_shape[2]:", x.shape[2])
        # print("x_shape[3]:", x.shape[3])
        # x = self.patch_embed(x)
        # if self.ape:
        #     x = x + self.absolute_pos_embed
        # x = self.pos_drop(x)
        fea_sr = []

        B, C, H, W = res_x4.shape
        res_x4 = res_x4.view(B, -1, C)

        x_up0, H, W = self.up_layer_pre(res_x4, H, W)  # 新增上采样层
        x = self.align_and_add(x_up0, res_x[-1], H1=H, W1=W, hw_shapes=hw_shapes, hw_shapes_idx=-1)
        x = self.layers[0](x, H, W)
        x_up1, H, W = self.up_layer0(x, H, W)

        # x = torch.cat([x_up1, res_x[-2]], dim=2)  # 在通道维度(dim=1)进行拼接
        x =self.align_and_add(x_up1, res_x[-2],H1=H, W1=W, hw_shapes=hw_shapes, hw_shapes_idx=-2)

        fea_sr.append(res_x[-1])

        x = self.layers[1](x, H, W)
        fea_sr.append(x)

        x_up2, H, W = self.up_layer1(x, H, W)

        # x = torch.cat([x_up2, res_x[-3]], dim=2)  # 在通道维度(dim=1)进行拼接
        x =self.align_and_add(x_up2, res_x[-3],H1=H, W1=W, hw_shapes=hw_shapes, hw_shapes_idx=-3)

        x = self.layers[2](x, H, W)
        fea_sr.append(x)
        # fea_sr = torch.cat(fea_sr, 1)

        x_up3, H, W = self.up_layer2(x, H, W)

        x =self.align_and_add(x_up3, res_x[-4],H1=H, W1=W, hw_shapes=hw_shapes, hw_shapes_idx=-4)  # 在通道维度(dim=1)进行拼接

        x = self.layers[3](x, H, W)

        x_out =self.align_and_add(x, res_x[0],H1=H, W1=W, hw_shapes=hw_shapes, hw_shapes_idx=-4)

        fea_sr.append(x_out)

        # for idx, layer in enumerate(self.layers):
        # x = layer(x, x_size)

        x_norm = self.norm(x_out)  # b seq_len c
        # print("x_patchembed shape:", x.shape)
        x = self.patch_unembed(x_norm, H, W)
        # print("x_patchunembed shape:", x.shape)
        # features_sr = []
        #
        # for l, feat in enumerate(fea_sr):
        #     feat = feat.view(-1, H/(2**l), W/(2**l), self.in_channels[l]).permute(0, 3, 1, 2).contiguous()
        #     features_sr.append(self.input_proj_sr[l](feat))

        return x, fea_sr

    def forward(self, res_x, res_x4,hw_shapes):
        # pad image to be divisible by window size
        # h, w = res_x[0].shape[2:]
        # ph, pw = 0, 0
        # if h % self.window_size != 0:
        #     ph = self.window_size - h % self.window_size
        # if w % self.window_size != 0:
        #     pw = self.window_size - w % self.window_size
        # x = torch.nn.functional.pad(x, pad=(0, pw, 0, ph), mode='reflect')
        #
        self.mean = self.mean.type_as(res_x[-1])
        # x = (x - self.mean) * self.img_range

        if self.upsampler == 'pixelshuffle':
            # for classical SR
            # x = self.conv_first(x)
            x, fea_sr = self.forward_features(res_x, res_x4,hw_shapes)
            # 获取最后一个输入特征图的高度和宽度
            # H, W = res_x4.shape[2], res_x4.shape[3]

            # features_sr = []
            # sr_flatten = []
            # for l, feat in enumerate(fea_sr):
            #     feat = feat.view(-1, H * (2 ** l), W * (2 ** l), self.in_channels[l]).permute(0, 3, 1, 2).contiguous()
            #     features_sr.append(self.input_proj_sr[l](feat))
            #
            # for lvl, feature in enumerate(reversed(features_sr)):
            #     bs, c, h, w = feature.shape
            #     spatial_shape = (h, w)
            #     # spatial_shapes.append(spatial_shape)
            #     feature = feature.flatten(2).transpose(1, 2)
            #     sr_flatten.append(feature)
            #
            # sr_flatten = torch.cat(sr_flatten, 1)  # bs, \sum{hxw}, c

            # spatial_shapes = torch.as_tensor(spatial_shapes, dtype=torch.long, device=features_sr.device)
            # level_start_index = torch.cat((spatial_shapes.new_zeros((1,)), spatial_shapes.prod(1).cumsum(0)[:-1]))

            x = self.sr_module(x)

            # x = self.conv_after_body(x)
            # x = self.conv_before_upsample(x)
            # x = self.conv_last(self.upsample(x))

        x = x + self.mean

        # return x[:,:,:h*self.upscale,:w*self.upscale]
        # return x, features_sr[-2]
        return x

    def flops(self):
        flops = 0
        h, w = self.patches_resolution
        flops += h * w * 3 * self.embed_dim * 9
        # flops += self.patch_embed.flops()
        for layer in self.layers:
            flops += layer.flops()
        flops += h * w * 3 * self.embed_dim * self.embed_dim
        flops += self.upsample.flops()
        return flops


if __name__ == '__main__':
    upscale = 4
    window_size = 8
    height = (1024 // upscale // window_size + 1) * window_size
    width = (720 // upscale // window_size + 1) * window_size
    model = SRNet(
        upscale=2,
        img_size=(height, width),
        window_size=window_size,
        img_range=1.,
        depths=[6, 6, 6, 6],
        embed_dim=60,
        num_heads=[6, 6, 6, 6],
        mlp_ratio=2,
        upsampler='pixelshuffledirect')
    print(model)
    print(height, width, model.flops() / 1e9)

    x = torch.randn((1, 3, height, width))
    x = model(x)
    print(x.shape)
